FROM ubuntu:20.04

USER root

RUN apt-get -y update

RUN apt-get -y install samba

RUN mkdir -pv /external_drive_1
RUN chmod -R 777 /external_drive_1
RUN mkdir -pv /external_drive_2
RUN chmod -R 777 /external_drive_2

ADD smb.conf /smb.conf

RUN cat /smb.conf >> /etc/samba/smb.conf

ENTRYPOINT ["/usr/sbin/smbd"]

CMD ["--foreground", "--no-process-group"]